[build]
  publish = "."
  functions = "."
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"

[context.dev.environment]
  NODE_ENV = "development"

[context.staging.environment]
  NODE_ENV = "staging"
